# Generated by Django 2.1.5 on 2019-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('set_cens', models.CharField(blank=True, default='', max_length=255)),
                ('areap', models.CharField(blank=True, default='', max_length=255)),
                ('cod_dist', models.CharField(blank=True, default='', max_length=255)),
                ('distrito', models.CharField(blank=True, default='', max_length=255)),
                ('cod_sub_pref', models.CharField(blank=True, default='', max_length=255)),
                ('sub_prefe', models.CharField(blank=True, default='', max_length=255)),
                ('regiao5', models.CharField(blank=True, default='', max_length=255)),
                ('regiao8', models.CharField(blank=True, default='', max_length=255)),
                ('nome_feira', models.CharField(default='', max_length=255)),
                ('registro', models.CharField(blank=True, default='', max_length=255)),
                ('logradouro', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=255)),
                ('referecia', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
