# Generated by Django 2.1.5 on 2019-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='areap',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='bairro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='cod_dist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='cod_sub_pref',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='distrito',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='logradouro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='nome_feira',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='numero',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='regiao5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='regiao8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='registro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='set_cens',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feira',
            name='sub_prefe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feira',
            name='long',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feira',
            name='referecia',
            field=models.CharField(default='', max_length=255),
        ),
    ]
