# Generated by Django 2.1.5 on 2019-01-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feira',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='feira',
            table='feira',
        ),
    ]
